version: '2'

services:
  swagger_tester:
    build:
      context: ./docker
      dockerfile: Dockerfile_dev
    volumes:
      - .:/opt/swagger_tester
      - rebar3:/root/.cache/rebar3
#    environment:
#     - DEBUG=1
    working_dir: /opt/swagger_tester

volumes:
  rebar3:
    driver: local
